apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-react-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: ${DOCKER_IMAGE_TAG}
        ports:
        - containerPort: 80
